<?php if ($this->success) { ?>
    <div class="alert alert-success">Product added!</div>
<?php } ?>
<?php if ($this->insertError) { ?>
    <div class="alert alert-error">Check the form please!.</div>
<?php } ?>
    
<?php
$this->form->prepare();
echo $this->form()->openTag($this->form);
echo $this->formRowTwb($this->form->get('product')->get('id'));
echo $this->formRowTwb($this->form->get('product')->get('name'));
echo $this->formRowTwb($this->form->get('product')->get('stock'));
echo $this->formSubmitTwb($this->form->get('submit'));
echo $this->form()->closeTag();